# Generated by Django 4.2.16 on 2024-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copyright", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer",
            },
        ),
    ]
