# Generated by Django 4.2.16 on 2024-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimonial", models.CharField(max_length=200)),
                ("author_name", models.CharField(max_length=200)),
                ("author_title", models.CharField(max_length=200)),
                ("author_photo", models.ImageField(upload_to="images")),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
    ]
